### PR TITLE
Load key and secret from environment if not provided

### LINKED ISSUE #48: Using within Lambda
How to pass credentials to node-ses `createClient()` so that it can send an email from within a Lmbda invocation?

Using the `AWS_ACCESS_KEY_ID` & `AWS_SECRET_ACCESS_KEY` from the environment variables automatically available inside the lambda doesn't work (not without also specifying session token, apparently)

### PR DESCRIPTION
**Pull request by tamlyn**
- Remove check for compulsory options.
- `aws4` automatically falls back to reading `key`, `secret` and `session` from the environment.

Closes #48

### CODE REVIEW

File: test/index.js [hunk 1]
```diff
@@ -74,24 +74,9 @@ describe('createClient', function(){
     assert.equal(client.amazon, 'http://www.google.com');
   });
 
-  it('should require a key', function(){
-    try {
-      ses.createClient();
-    } catch (err) {
-      if (!/key is required/.test(err)) {
-        throw err;
-      }
```
Comment (tamlyn) [inline test/index.js]: FYI these tests didn't fail, even when I removed the `expect` check. Because if `ses.createClient()` *doesn't* throw then the test passes regardless.

**Comment by markstos** [comment]
Thanks for this. I'm a Lambda user as well and may need this one day.
